name: Node.js CI

on: [push]

jobs:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.10.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ 12.10.0}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ 12.10.0 }}
    - run: npm install
    - run: npm test
      env:
        CI: true
